apis/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.getRoutes, name='get-routes'),
    path('all-confrences/', views.getAllConferences, name='get-all-conferences'),
    path('conference/<str:conference_id>/', views.a_conference, name='get-conference'),
    path('talk/<str:talk_id>/', views.a_talk, name='get-talk'),
    path('create-conference/', views.create_conference, name='create-conference'),
    path('create-talk/<str:conference_id>/', views.create_talk, name='create-talk'),
    path('edit-conference/<str:conference_id>/', views.edit_conference, name='edit-conference'),
    path('edit-talk/<str:talk_id>/', views.edit_talk, name='edit-talk'),
    path('add-speaker/<str:talk_id>/', views.add_speaker, name='add-speaker'),
    path('get-speakers/<str:talk_id>/', views.get_talk_speakers, name='get-speakers'),
    path('get-participants/<str:talk_id>/', views.get_talk_participants, name='get-participants'),
    path('conference/<str:conference_id>/talks/', views.get_conference_talks, name='get-conference-talks'),
    path('remove-speaker/<talk_id>/', views.remove_speaker, name='remove-speaker'),
    path('add-participant/<str:talk_id>/', views.add_participant, name='add-participant'),
    path('remove-participant/<str:talk_id>/', views.remove_participant, name='remove-participant'),
]

conference_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.loginPage, name='login'),
    path('register/', views.registerPage, name='register'),
    path('logout/', views.logoutUser, name='logout'),
    path('create-conference/', views.createConference, name='create-conference'),
    path('conference/<str:conference_id>/', views.viewConference, name='view-conference'),
    path('edit-conference/<str:conference_id>/', views.editConference, name='edit-conference'),
    path('create-talk/<str:conference_id>/', views.createTalk, name='create-talk'),
    path('talk/<str:talk_id>/', views.viewTalk, name='view-talk'),
    path('edit-talk/<str:talk_id>/', views.editTalk, name='edit-talk'),
    path('add-speaker/<str:talk_id>/', views.addSpeaker, name='add-speaker'),
    path('remove-speaker/<str:talk_id>/', views.removeSpeaker, name='remove-speaker'),
    path('add-participants/<str:talk_id>/', views.addParticipant, name='add-participant'),
    path('remove-participant/<str:talk_id>/', views.removeParticipant, name='remove-participant'),
    path('profile/<username>/', views.profile, name='profile'),
    ]   

conference_mgt_sys_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('api/', include('apis.urls')), 
    path('admin/', admin.site.urls),
    path('', include('conference_app.urls')),
    path('', include('django.contrib.auth.urls')),
                 
]

conference_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

#the user model
class User(AbstractUser):
    full_name = models.CharField(max_length=250, null=True)
    email = models.EmailField(unique=True)

    USERNAME_FIELD = 'email'
    
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email + ' ' + str(self.full_name)

#the conference model
class Conference(models.Model):
    host = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=450)
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return self.title


#the talk model
class Talk(models.Model):
    host = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=450)
    description = models.TextField()
    speakers = models.ManyToManyField(User, related_name='speakers', blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    conference = models.ForeignKey(Conference, on_delete=models.CASCADE)
    date_time = models.DateTimeField()
    duration = models.CharField(max_length=150)

    def __str__(self):
        return self.title + ' ' + str(self.conference)


    

conference_app/forms.py
from django.forms import ModelForm
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.admin import widgets 

#custom signup/ register form
class SignupForm(UserCreationForm):
    full_name = forms.CharField(max_length = 200)
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ('full_name', 'username', 'email','password1', 'password2')

    def __init__ (self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)


        self.fields['full_name'].widget.attrs['class']= 'form-control'
        self.fields['username'].widget.attrs['class']= 'form-control'
        self.fields['email'].widget.attrs['class']= 'form-control'
        self.fields['password1'].widget.attrs['class']= 'form-control'
        self.fields['password2'].widget.attrs['class']= 'form-control'


# add and edit conference form
class ConferenceForm(ModelForm):
    class Meta:
        model = Conference
        exclude = ['host']
        fields = ['title', 'description', 'start_date', 'end_date']

        widgets={
            'title':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Conference title'}),
            'description':forms.Textarea(attrs={'class':'form-control', 'placeholder':'Conference description'}),
            'start_date':forms.TextInput(attrs={'class':'form-control',  'placeholder':'The first day of the conference'}),
            'end_date':forms.TextInput(attrs={'class':'form-control',  'placeholder':'The last day of the conference'}),
        }
        def __init__(self, *args, **kwargs):
            super(ConferenceForm, self).__init__(*args, **kwargs)

class TalkForm(ModelForm):
    class Meta:
        model = Talk
        exclude = ['host', 'conference']
        fields = ['title', 'description', 'speakers', 'participants', 'date_time', 'duration']

        widgets={
            'title':forms.TextInput(attrs={'class':'form-control', 'placeholder':'Talk title'}),
            'description':forms.Textarea(attrs={'class':'form-control', 'placeholder':'Talk description'}),
            'date_time':forms.DateTimeInput(attrs={'class':'form-control'}),
            'speakers':forms.SelectMultiple(choices=User.objects.all(), attrs={'class':'form-control'}),
            'participants':forms.SelectMultiple(choices=User.objects.all(), attrs={'class':'form-control'}),
            'duration':forms.TextInput(attrs={'class':'form-control',  'placeholder':'Talk duration'}),
        }

        def __init__(self, *args, **kwargs):
            super(TalkForm, self).__init__(*args, **kwargs)

class AddSpeakerForm(ModelForm):
    class Meta:
        model = Talk
        fields = ['speakers']

        widgets={
            'speakers':forms.SelectMultiple(choices=User.objects.all(), attrs={'class':'form-control'}),
        }

        def __init__(self, *args, **kwargs):
            super(AddSpeakerForm, self).__init__(*args, **kwargs)

class RemoveSpeakerForm(ModelForm):
    class Meta:
        model = Talk
        fields = ['speakers']

        widgets={
            'speakers':forms.SelectMultiple(choices=Talk.objects.all().values_list('speakers', 'speakers'), attrs={'class':'form-control'}),
        }

        def __init__(self, *args, **kwargs):
            super(RemoveSpeakerForm, self).__init__(*args, **kwargs)

        
class AddParticipantForm(ModelForm):
    class Meta:
        model = Talk
        fields = ['participants']

        widgets={
            'participants':forms.SelectMultiple(choices=User.objects.all(), attrs={'class':'form-control'}),
        }

        def __init__(self, *args, **kwargs):
            super(AddParticipantForm, self).__init__(*args, **kwargs)

class RemoveParticipantForm(ModelForm):
    class Meta:
        model = Talk
        fields = ['participants']

        widgets={
            'participants':forms.SelectMultiple(choices=Talk.objects.all().values_list('participants', 'participants'), attrs={'class':'form-control'}),
        }

        def __init__(self, *args, **kwargs):
            super(RemoveParticipantsForm, self).__init__(*args, **kwargs)

conference_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import *
from django.contrib.auth.decorators import login_required
from .models import *


# Create your views here.

#custom login view
def loginPage(request):
    context = {}
    if request.user.is_authenticated:
        return redirect('home')

    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            user = User.objects.get(email=email)
        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
             
    return render(request,'registration/login.html', context)

#custom register view
def registerPage(request):
    form = SignupForm
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect ('home')
        else:
            messages.error(request, 'An error occured during registration')

    return render(request, 'registration/register.html', {'form':form})

#custom logout view
def logoutUser(request):
    logout(request)
    return redirect('home')

def home(request):
    conferences = Conference.objects.all()
    context = {'conferences':conferences}
    return render(request, 'home.html', context)

@login_required(login_url='login')
def createConference(request):
    form = ConferenceForm
    if request.method == 'POST':
        form = ConferenceForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.host = request.user  
            form.save()
            return redirect('home')
        else:
            messages.error(request, 'An error occured during conference creation')

    return render(request, 'conference.html', {'form':form})


@login_required(login_url='login')
def editConference(request, conference_id):
    conference = Conference.objects.get(pk=conference_id)
    if request.user == conference.host:
        form = ConferenceForm(instance=conference)
        if request.method == 'POST':
            form = ConferenceForm(request.POST, instance=conference)
            if form.is_valid():
                form.save()
                return redirect ('home')
        return render(request, 'conference.html', {'form':form})
    else:
        return redirect('home')

def viewConference(request, conference_id):
    conference = Conference.objects.get(pk=conference_id)
    talks = Talk.objects.filter(conference=conference)
    context = {'conference':conference, 'talks':talks}
    return render(request, 'view-conference.html', context)

@login_required(login_url='login')
def createTalk(request, conference_id):
    form = TalkForm
    conference = Conference.objects.get(pk=conference_id)
    if request.method == 'POST':
        form = TalkForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.host = request.user 
            form.conference = conference
            form.save()
            return redirect('home')
        else:
            messages.error(request, 'An error occured during talk creation')

    return render(request, 'talk.html', {'form':form})


@login_required(login_url='login')
def editTalk(request, talk_id):
    talk = Talk.objects.get(pk=talk_id)
    if request.user == talk.host:
        form = TalkForm(instance=talk)
        if request.method == 'POST':
            form = TalkForm(request.POST, instance=talk)
            if form.is_valid():
                form.save()
                return redirect ('home')
        return render(request, 'talk.html', {'form':form})
    else:
        return redirect('home')

@login_required(login_url='login')
def addSpeaker(request, talk_id):
    form = AddSpeakerForm
    talk = Talk.objects.get(pk=talk_id)
    if request.user == talk.host:
        if request.method == 'POST':
            speaker = request.POST.get('speakers')
            talk.speakers.add(speaker)
            return redirect ('view-talk', talk_id=talk.id)
        return render(request, 'speaker.html', {'form':form})
    else:
        return redirect('home')

@login_required(login_url='login')
def removeSpeaker(request, talk_id):
    form = RemoveSpeakerForm
    talk = Talk.objects.get(pk=talk_id)
    if request.user == talk.host:
        if request.method == 'POST':
            speaker = request.POST.get('speakers')
            talk.speakers.remove(speaker)
            return redirect ('view-talk', talk_id=talk.id)
        return render(request, 'speaker.html', {'form':form})
    else:
        return redirect('home')

def viewTalk(request, talk_id):
    talk = Talk.objects.get(pk=talk_id)
    conference = talk.conference
    context = {'conference':conference, 'talk':talk}
    return render(request, 'view-talk.html', context)

@login_required(login_url='login')
def addParticipant(request, talk_id):
    form = AddParticipantForm
    talk = Talk.objects.get(pk=talk_id)
    if request.user == talk.host:
        if request.method == 'POST':
            participant = request.POST.get('participants')
            talk.participants.add(participant)
            return redirect ('view-talk', talk_id=talk.id)
        return render(request, 'participants.html', {'form':form})
    else:
        return redirect('home')


@login_required(login_url='login')
def removeParticipant(request, talk_id):
    form = RemoveParticipantForm
    talk = Talk.objects.get(pk=talk_id)
    if request.user == talk.host:
        if request.method == 'POST':
            participant = request.POST.get('participants')
            talk.participants.remove(participant)
            return redirect ('view-talk', talk_id=talk.id)
        return render(request, 'participants.html', {'form':form})
    else:
        return redirect('home')


def profile(request, username):
    user = User.objects.get(username=username)
    conferences = Conference.objects.filter(host=user)
    context = {'user':user, 'conferences':conferences}
    return render(request, 'profile.html', context)

conference_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />

    <!--- jquery -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>

    <!-- Fengyuan Chen's Datepicker -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.css"
      integrity="sha256-b88RdwbRJEzRx95nCuuva+hO5ExvXXnpX+78h8DjyOE="
      crossorigin="anonymous"
    />
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/0.6.5/datepicker.min.js"
      integrity="sha256-/7FLTdzP6CfC1VBAj/rsp3Rinuuu9leMRGd354hvk0k="
      crossorigin="anonymous"
    ></script>
    <title>Conference MGT SYS</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Conference MGT SYS</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'create-conference' %}">Create Conference</a>
            </li>
             </ul>

            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% else %}
         

          <li>
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>

          <li>
              <a class="nav-link" href="{% url 'register' %}">Sign Up</a>
          </li>
         
          {% endif %}}
          <!-- <ul class="nav justify-content-end">
        <li class="nav-item"><a class="nav-link" href="{% url 'register'%}">Sign up</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Log in</a></li>
      </ul> -->
        </div>
      </div>
    </nav>
    {% block content %} {% endblock %}
  </body>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"
  ></script>
</html>

conference_app/templates/conference.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div style="margin-top: 20px;" class="container">
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input class="btn btn-secondary btn-sm" type="submit" value="Submit">
    </form>
</div>


<script>
    $(function () {
      $("#id_start_date").datepicker();
    });
  </script>

  <script>
    $(function () {
      $("#id_end_date").datepicker();
    });
  </script>
{% endblock %}

conference_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<div style="margin-top: 20px;" class="container">
  {% if conferences %} 
  <div class="row">
      {% for conference in conferences %}
    <div style="margin-bottom: 15px;" class="col-sm-6">
      <div style="height: 200px;" class="card">
        <div class="card-body">
          <h5 class="card-title">{{conference.title}}</h5>
          <p class="card-text">{{conference.description}}</p>
          <a href="{% url 'view-conference' conference.pk %}" class="btn btn-secondary">View Conference</a>
        </div>
      </div>
    </div>
     {% endfor %}
  </div>
  {% else %}
  <p>There are no conference</p>
  {% endif %}
</div>

{% endblock %}

conference_app/templates/participants.html
{% extends 'base.html' %}

{% block content %}
<div style="margin-top: 20px;" class="container">
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input class="btn btn-secondary btn-sm" type="submit" value="Submit">
    </form>
</div>
{% endblock %}

conference_app/templates/profile.html
{% extends 'base.html' %} {% block content %}
<div style="margin-top: 20px" class="container">
  <h2 style="text-align: center">{{user.full_name}}</h2>
  <h3 style="text-align: center">Username: {{user.username}}</h3>
  <h4 style="text-align: center">User Id: {{user.id}}</h4>

  <div style="margin-top: 60px;">
    <h2 style="text-align: center;">Conference Hosted</h2>
    {% if conferences %}
    <div class="row">
      {% for conference in conferences %}
      <div style="margin-bottom: 15px" class="col-sm-6">
        <div style="height: 200px" class="card">
          <div class="card-body">
            <h5 class="card-title">{{conference.title}}</h5>
            <p class="card-text">{{conference.description}}</p>
            <a href="{% url 'view-conference' conference.pk %}" class="btn btn-secondary">View Conference</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% else %}
    <p>There are no conference</p>
    {% endif %}
  </div>
</div>

{% endblock %}

conference_app/templates/speaker.html
{% extends 'base.html' %}

{% block content %}
<div style="margin-top: 20px;" class="container">
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input class="btn btn-secondary btn-sm" type="submit" value="Submit">
    </form>
</div>
{% endblock %}

conference_app/templates/talk.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div style="margin-top: 20px;" class="container">
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input class="btn btn-secondary btn-sm" type="submit" value="Submit">
    </form>
</div>
{% endblock %}

conference_app/templates/view-conference.html
{% extends 'base.html' %}

{% block content %}
    <div style="margin-top: 20px;" class="container">
        <h2 style="text-align: center;">{{conference.title}}</h2>
        {% if request.user == conference.host %}
        <p style="text-align:right;"><a href="{% url 'edit-conference' conference.id %}">Edit conference</a></p>
        {% endif %}
        <p><a href="{% url 'profile' conference.host.username %}">{{conference.host}}</a></p>
        <div>
            {{conference.description}}
        </div>
        <P>{{conference.start_date}} - {{conference.end_date}}</P>

        {% if talks %}
        <h3 style="text-align: center;">Talks</h3>
        <p style="text-align: right;"><a href="{% url 'create-talk' conference.id %}"> add a talk</a></p>
        {% for talk in talks %}
        <h4><a href="{% url 'view-talk' talk.pk %}">{{talk.title}}</a></h4>
        {% endfor %}
        {% else %}
        <h4 style="text-align: center;">There are no Talks yet, <span><a href="{% url 'create-talk' conference.id %}"> add a talk</a></span></h4>
        {% endif %}
    </div>

{% endblock %}

conference_app/templates/view-talk.html
{% extends 'base.html' %}

{% block content %}
<div style="margin-top: 20px;" class="container">
    <h2 style="text-align: center;">{{talk.title}}</h2>
    {% if request.user == talk.host %}
    <p style="text-align: right;"><a href="{% url 'edit-talk' talk.pk %}">Edit talk</a></p>
    {% endif %}
    <p style="text-align: right;">{{conference}} Conference</p> 
    <div>
        {{talk.description}}
        <ul>
            <li>Duration: {{talk.duration}}</li>
            <li>Date and Time: {{talk.date_time}}</li>
        </ul>
        <p>Talk Host: {{talk.host}}</p>
    </div>

    <div class="row">
        <div class="col">
            <h2>Speakers</h2>

           
            {% if talk.speakers.all %}
             {% if request.user == talk.host %}
             <p><a href="{% url 'add-speaker' talk_id=talk.id%}">Add speaker</a></p>
            <p><a href="{% url 'remove-speaker' talk_id=talk.id%}">Remove speaker</a></p>
            {% endif %}
            <ul>
                {% for speaker in talk.speakers.all %}
                <li><a href="{% url 'profile' speaker.username %}">{{speaker.full_name}} - {{speaker.email}}</a></li>
                {% endfor %}
            </ul>
            {% else %}
            <p>There are no speakers</p>
            <p><a href="{% url 'add-speaker' talk.id %}">Add speakers</a></p>
            {% endif %}
        </div>
        <div class="col">
            <h2>Participants</h2>
            {% if talk.participants.all %}
            {% if request.user == talk.host or talk.speakers %}
             <p><a href="{% url 'add-participant' talk_id=talk.id%}">Add participant</a></p>
            <p><a href="{% url 'remove-participant' talk_id=talk.id%}">Remove participant</a></p>
            {% endif %}
            <ul>
                {% for participant in talk.participants.all %}
                <li><a href="{% url 'profile' participant.username %}">{{participant.full_name}} - {{participant.email}}</a></li>
                {% endfor %}
            </ul>
            {% else %}
            <p>There are no participants</p>
            <p><a href="{% url 'add-participant' talk.id %}">Add participant</a></p>
    
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}